elevenlabs/elevenlabs-python

elevenlabs/api/history.py

If there is some feedback in history item it crashes as it expects string. This should fix it.

Add model for feedback in history, otherwise it crashes

---

.gitignore
elevenlabs/api/history.py
elevenlabs/api/user.py
elevenlabs/api/voice.py
elevenlabs/simple.py

This PR brings support to multiple endpoints that I noticed were not supported in this wrapper:
1. `/v1/voices/settings/default`
2. `/v1/voices/{voice_id}/settings`
3. `/v1/voices/{voice_id}/settings/edit`
4. `/v1/voices/{voice_id}`
5. `/v1/voices/{voice_id}/edit`
6. `/v1/history/{history_item_id}`
7. `/v1/user/subscription`
I've also modified the following:
1. `Subscription` class: Added new properties.
2. `User` class: the `from_api` function was not working so I fixed it.

New functions for unsupported endpoints + some modifications

---

elevenlabs/api/voice.py

For the application I'm building, I need the `preview_url`. I figured I might just as well create a commit for the official ElevenLabs Python package instead of creating a separate method.
I believe there are more parameters returned by the API that are not covered in the package. Those would be (directly from your API, but I cut out the existing parameters):
```
{
"fine_tuning": {
"model_id": null,
"language": null,
"is_allowed_to_fine_tune": false,
"fine_tuning_requested": false,
"finetuning_state": "not_started",
"verification_attempts": null,
"verification_failures": [],
"verification_attempts_count": 0,
"slice_ids": null
},
"available_for_tiers": [],
"sharing": null
},
```
But those parameters might be for another PR 🙂

Add the 'preview_url' parameter to Voice API

---

elevenlabs/api/history.py
elevenlabs/api/voice.py

The current implementation of `root_validator` for `VoiceClone` class is broken (supposedly the same is true for `HistoryItem`) because the validator is being called even if the prior default field validation failed. In particular, this leads to a very confusing and annoying behaviour when the user passes more than 25 files for voice cloning:
```python
from api import Voice, VoiceClone
Voice.from_clone(VoiceClone(name="dummy", description="dummy", files=["dummy"] * 26))
```
The above code results in the following error which is really obscure and hard to debug:
```
Traceback (most recent call last):
File "/home/george/code/elevenlabs-python/elevenlabs/test.py", line 5, in <module>
Voice.from_clone(VoiceClone(name="dummy", description="dummy", files=["dummy"] * 26))
File …
```

Fix pydantic model validation

---

elevenlabs/api/tts.py
elevenlabs/simple.py

Hey there the Python wrapper did not have access to this URL param, so I added it.
based on this:  https://help.elevenlabs.io/hc/en-us/articles/15726761640721-Can-I-reduce-API-latency-
Tested locally and with `optimize_streaming_latency=3` it's WAAAY faster

added optimize_streaming_latency param

---

elevenlabs/api/tts.py
elevenlabs/simple.py

One question remains, as per API docs, mp3 output format for websocket is only mp3_44100 , but does it also support specifying bit rate ?

Add output_format to client library.

---

src/elevenlabs/client.py
src/elevenlabs/realtime_tts.py
tests/test_async_generation.py

Why:
Allowing the async client to utilize incoming text streams when generating voice. Very useful when feeding the realtime output of an LLM into the TTS.
Closes #344
What:
1. Copied `RealtimeTextToSpeechClient` and `text_chunker` into `AsyncRealtimeTextToSpeechClient` and `async_text_chunker` Most of the logic is intact, aside from async stuff
2. Added `AsyncRealtimeTextToSpeechClient` into `AsyncElevenLabs` just like `RealtimeTextToSpeechClient` is in `ElevenLabs`
3. Added rudimentary testing
The code is basically a copy-paste of what I found in the repo. We can rewrite it to be more elegant, but I figured parity with the sync code is more important.

(feat): Support for text iterators in `AsyncElevenLabs`

---

.github/ISSUE_TEMPLATE/1-bug_report.yml
.github/ISSUE_TEMPLATE/2-feature_request.yml
.github/ISSUE_TEMPLATE/config.yml

Adds structured templates to submit either a feedback request/bug fix, new issues are now automatically tagged on creation.
TODO: Make sure people do not use issues for security incident reports.

feat: add issue templates

---

.fernignore
poetry.lock
pyproject.toml
src/elevenlabs/conversation.py
src/elevenlabs/conversational_ai/conversation.py
src/elevenlabs/conversational_ai/default_audio_interface.py

Early prototype, subject to change based on user feedback.
Takes care of the websocket session and message handling, exposing a simplified audio interface to the client that can be hooked up to the appropriate audio inputs / outputs based on the usecase.
Also implements a basic speaker/microphone interface, via optional dependency on pyaudio.

Implement basic SDK for convai agents

---

.fernignore

Need to have that generated, should support the features we need for the manually added stuff in #399 (and #389). But need to merge this first before being able to test the generated SDK preview.

Remove pyproject.toml + poetry.lock from .fernignore

---

src/elevenlabs/conversational_ai/conversation.py

Was running into an error when using the Python [convAI example code](https://github.com/elevenlabs/elevenlabs-examples/tree/main/examples/conversational-ai/python): AttributeError: 'ElevenLabs' object has no attribute 'get_signed_url'  
Bug reported by user: https://github.com/elevenlabs/elevenlabs-python/issues/413 
This change seems to fix it when tested locally.

Update get_signed_url for conversation.py

---

src/elevenlabs/conversational_ai/conversation.py

Avoid using mutable default values for _should_stop by initializing it in the __init__ method to ensure instance-level independence.

Move _should_stop initialization to __init__

---

src/elevenlabs/conversational_ai/conversation.py

Fixes #417 
Why:
Class-level attributes persisted state between sessions. Making them instance-level ensures each session starts fresh.
What:
Moved `_thread`, `_should_stop`, `_conversation_id`, and `_last_interrupt_id` from class-level to instance-level within the __init__ method.
Note: This pull request is a proof of concept, demonstrating how moving class-level attributes to instance-level resolves the session interference issue. I understand this can’t be merged directly due to the code generation process.

fix: move class-level attributes to instance-level in Conversation class

---

.gitignore
src/elevenlabs/conversational_ai/conversation.py
tests/e2e_test_convai.py
tests/test_convai.py

Add support for client-tools in Python

feat: Client Tools

---

src/elevenlabs/conversational_ai/conversation.py
tests/test_convai.py

python conversational AI SDK doesnt currently support passing dynamic-variables, this simple PR fixes it. 
verified by running locally

fix: add dynamic variables support to conversation configuration

---

pyproject.toml

This patch updates pyproject.toml to allow tools like uv to install this package from source.
It seems that having `project.urls` along with `tool.poetry` is not spec compliant, pip itself seems to be more permissive but uv refuses to install this project from source. See [astral-sh/uv issue #6419](https://github.com/astral-sh/uv/issues/6419) for more details on the toml stuff.
As an fyi, using project.urls.repository field seems to have no effect on the [PyPI listing](https://pypi.org/project/elevenlabs/1.7.0/) of the package: 
If needed, I can open this up as an issue, as this repository is codegen'ed.

(fix): move repository url field into tool.poetry namespace

---

.github/workflows/ci.yml
.github/workflows/tests.yml

From github notification:
> The Ubuntu 20.04 runner image will be fully unsupported by April 1, 2025.
> Jobs using the ubuntu-20.04 YAML workflow label should be updated to
ubuntu-22.04, ubuntu-24.04 or ubuntu-latest.

Bump CI runners from ubuntu-20.04 to ubuntu-24.04

---

src/elevenlabs/conversational_ai/conversation.py

Sometimes using the ConversationalAI [demo](https://github.com/elevenlabs/elevenlabs-examples/blob/main/examples/conversational-ai/python/convai/demo.py) throwing exceptions like:
- `Error receiving message: sent 1009 (message too big) frame with 1254313 bytes exceeds limit of 1048576 bytes; no close frame received`
- `Error sending user audio chunk: sent 1009 (message too big) frame with 1254313 bytes exceeds limit of 1048576 bytes; no close frame received`
Seems current ws message limit is too low for some provided sound answers. This fix should fits long response requirements.

Fix: Error receiving message & Error sending user audio chunk sent 1009 (message too big)

---

README.md
src/elevenlabs/client.py

Deprecate `generate` and `clone` methods and update the readme to not use them.

[SDK v2] Deprecate generate and clone

---

src/elevenlabs/conversational_ai/conversation.py
tests/test_async_convai.py
tests/test_convai.py

Fixes https://github.com/elevenlabs/elevenlabs-python/issues/619

Fix issue with conversation when no auth is required
